stages:
  train:
    cmd: python train.py
    deps:
      - samsung_train.txt
      - samsung_train_labels.txt
    outs:
      - model.pkl
  dvc_add_train:
    cmd: dvc add model.pkl
    deps:
      - model.pkl
  infer:
    cmd: python infer.py
    deps:
      - model.pkl
      - samsung_test.txt
      - samsung_test_labels.txt
    outs:
      - predictions.txt
      - metrics.txt
  dvc_add_infer:
    cmd: dvc add predictions.txt metrics.txt
    deps:
      - predictions.txt
      - metrics.txt    
  dvc_push:
    cmd: dvc push  